onlyBuiltDependencies:
  - "@embedded-postgres/windows-x64"
  - "@embedded-postgres/linux-x64"
  - "@embedded-postgres/darwin-arm64"
  - "@embedded-postgres/darwin-x64"
  - "@prisma/engines"
  - esbuild
  - prisma
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
