import "server-only";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { env } from "@/lib/env";

/**
 * Private object storage for documents. Keys are generated by the server
 * (`users/{userId}/{random}`); nothing stored here is ever reachable by URL,
 * only through the authenticated download route.
 *
 * The local-disk driver suits a self-hosted install. A hosted deployment
 * with an ephemeral disk needs an S3-compatible driver behind the same
 * interface (docs/security.md §7).
 */
export type StorageAdapter = {
  put(key: string, bytes: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array>;
  delete(key: string): Promise<void>;
};

const KEY_RE = /^users\/[A-Za-z0-9_-]{1,64}\/[A-Za-z0-9_-]{16,64}$/;

export function assertStorageKey(key: string): void {
  if (!KEY_RE.test(key)) throw new Error("Invalid storage key");
}

export function localDiskStorage(root: string): StorageAdapter {
  const base = path.resolve(root);
  const resolve = (key: string) => {
    assertStorageKey(key);
    const full = path.resolve(base, key);
    // Defence in depth: the key format already rules out traversal.
    if (!full.startsWith(base + path.sep)) throw new Error("Invalid storage key");
    return full;
  };
  return {
    async put(key, bytes) {
      const full = resolve(key);
      await mkdir(path.dirname(full), { recursive: true });
      // Write then rename, so a crash never leaves a half-written document.
      const temp = `${full}.${process.pid}.tmp`;
      await writeFile(temp, bytes, { flag: "wx", mode: 0o600 });
      await rename(temp, full);
    },
    async get(key) {
      return new Uint8Array(await readFile(resolve(key)));
    },
    async delete(key) {
      await rm(resolve(key), { force: true });
    },
  };
}

let storage: StorageAdapter | null = null;

export function getStorage(): StorageAdapter {
  storage ??= localDiskStorage(env.STORAGE_DIR);
  return storage;
}
